// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/user.proto

package cmd.user;

public interface LoginResultOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int32 result = 1;
  /**
   * <code>required int32 result = 1;</code>
   *
   * <pre>
   *大于0成功，小于零失败
   * </pre>
   */
  boolean hasResult();
  /**
   * <code>required int32 result = 1;</code>
   *
   * <pre>
   *大于0成功，小于零失败
   * </pre>
   */
  int getResult();
}
