namespace Mogo.RPC
{
    using System;

    public enum MissionReq : byte
    {
        ADD_FRIEND_DEGREE = 0x15,
        CLIENT_MISSION_INFO = 0x10,
        CREATE_CLIENT_DROP = 0x4a,
        ENTER_MISSION = 1,
        EXIT_MISSION = 2,
        GET_ACQUIRED_MISSION_BOSS_TREASURE = 0x52,
        GET_FINISHED_MISSIONS = 7,
        GET_MISSION_BOSS_TREASURE = 0x53,
        GET_MISSION_LEFT_TIME = 10,
        GET_MISSION_RECORD = 80,
        GET_MISSION_REWARDS = 15,
        GET_MISSION_SWEEP_LIST = 0x42,
        GET_MISSION_TIMES = 6,
        GET_MISSION_TRESURE = 0x49,
        GET_MISSION_TRESURE_REWARDS = 0x18,
        GET_NOTIFY_TO_CLENT_EVENT = 8,
        GET_RESET_TIMES = 0x43,
        GET_RESET_TIMES_BY_MISSION = 0x44,
        GET_REVIVE_TIMES = 0x1a,
        GET_STAR_MISSION = 4,
        GO_TO_INIT_MAP = 0x47,
        KILL_MONSTER_EXP = 0x13,
        MSG_GET_SWEEP_TIMES = 0x48,
        MSG_SWEEP_MISSION = 0x12,
        MWSY_MISSION_ENTER = 0x56,
        MWSY_MISSION_GET_INFO = 0x55,
        MWSY_MISSION_NOTIFY_CLIENT = 0x54,
        NOTIFY_TO_CLENT_SPAWNPOINT = 0x16,
        NOTIFY_TO_CLIENT_MISSION_INFO = 0x51,
        NOTIFY_TO_CLIENT_MISSION_REWARD = 0x4b,
        NOTIFY_TO_CLIENT_RESULT = 9,
        NOTIFY_TO_CLIENT_RESULT_FAILED = 14,
        NOTIFY_TO_CLIENT_RESULT_SUCCESS = 13,
        NOTIFY_TO_CLIENT_TO_LOAD_ITNI_MAP = 0x4f,
        NOTIFY_TO_CLIENT_TO_UPLOAD_COMBO = 0x45,
        QUIT_MISSION = 20,
        RESET_MISSION_TIMES = 5,
        REVIVE = 0x19,
        SPAWNPOINT_START = 11,
        SPAWNPOINT_STOP = 12,
        START_MISSION = 3,
        UPLOAD_COMBO = 0x17,
        UPLOAD_COMBO_AND_BOTTLE = 0x4c
    }
}

