// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/user.proto

package cmd.user;

public interface LoginResultOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .cmd.user.LoginResult.Result result = 1;
  /**
   * <code>required .cmd.user.LoginResult.Result result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>required .cmd.user.LoginResult.Result result = 1;</code>
   */
  cmd.user.LoginResult.Result getResult();
}
