//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/gt_oxex.proto
// Note: requires additional types generated from: gt_base.proto
namespace gt_msg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TagTableStatus")]
  public partial class TagTableStatus : global::ProtoBuf.IExtensible
  {
    public TagTableStatus() {}
    
    private bool _cbtablelock;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cbtablelock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbtablelock
    {
      get { return _cbtablelock; }
      set { _cbtablelock = value; }
    }
    private bool _cbplaystatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cbplaystatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbplaystatus
    {
      get { return _cbplaystatus; }
      set { _cbplaystatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"tagUserStatus")]
  public partial class tagUserStatus : global::ProtoBuf.IExtensible
  {
    public tagUserStatus() {}
    
    private int _wTableID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wTableID
    {
      get { return _wTableID; }
      set { _wTableID = value; }
    }
    private int _wChairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wChairID
    {
      get { return _wChairID; }
      set { _wChairID = value; }
    }
    private int _cbUserStatus;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cbUserStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cbUserStatus
    {
      get { return _cbUserStatus; }
      set { _cbUserStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonUserID")]
  public partial class LogonUserID : global::ProtoBuf.IExtensible
  {
    public LogonUserID() {}
    
    private string _user_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _user_password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"user_password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string user_password
    {
      get { return _user_password; }
      set { _user_password = value; }
    }
    private int _user_Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"user_Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_Version
    {
      get { return _user_Version; }
      set { _user_Version = value; }
    }
    private int _user_LoginType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"user_LoginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int user_LoginType
    {
      get { return _user_LoginType; }
      set { _user_LoginType = value; }
    }
    private string _kindtype;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"kindtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string kindtype
    {
      get { return _kindtype; }
      set { _kindtype = value; }
    }
    private string _strMachineID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"strMachineID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string strMachineID
    {
      get { return _strMachineID; }
      set { _strMachineID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonRoomFail")]
  public partial class LogonRoomFail : global::ProtoBuf.IExtensible
  {
    public LogonRoomFail() {}
    
    private int _failCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"failCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int failCode
    {
      get { return _failCode; }
      set { _failCode = value; }
    }
    private string _failstring;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"failstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string failstring
    {
      get { return _failstring; }
      set { _failstring = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogonRoomSuccess")]
  public partial class LogonRoomSuccess : global::ProtoBuf.IExtensible
  {
    public LogonRoomSuccess() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserRoomEnter")]
  public partial class UserRoomEnter : global::ProtoBuf.IExtensible
  {
    public UserRoomEnter() {}
    
    private gt_msg.User _user;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"user", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public gt_msg.User user
    {
      get { return _user; }
      set { _user = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfigServer")]
  public partial class ConfigServer : global::ProtoBuf.IExtensible
  {
    public ConfigServer() {}
    
    private int _wTableCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wTableCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wTableCount
    {
      get { return _wTableCount; }
      set { _wTableCount = value; }
    }
    private int _wChairCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wChairCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wChairCount
    {
      get { return _wChairCount; }
      set { _wChairCount = value; }
    }
    private int _wServerType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"wServerType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wServerType
    {
      get { return _wServerType; }
      set { _wServerType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemMessage")]
  public partial class SystemMessage : global::ProtoBuf.IExtensible
  {
    public SystemMessage() {}
    
    private string _szstring;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"szstring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szstring
    {
      get { return _szstring; }
      set { _szstring = value; }
    }
    private int _wType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wType
    {
      get { return _wType; }
      set { _wType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomTabInfo_OxEx")]
  public partial class RoomTabInfo_OxEx : global::ProtoBuf.IExtensible
  {
    public RoomTabInfo_OxEx() {}
    
    private int _tablecount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tablecount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tablecount
    {
      get { return _tablecount; }
      set { _tablecount = value; }
    }
    private readonly global::System.Collections.Generic.List<gt_msg.TagTableStatus> _tablestatusary = new global::System.Collections.Generic.List<gt_msg.TagTableStatus>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tablestatusary", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gt_msg.TagTableStatus> tablestatusary
    {
      get { return _tablestatusary; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserSitDown")]
  public partial class UserSitDown : global::ProtoBuf.IExtensible
  {
    public UserSitDown() {}
    
    private int _wtableid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wtableid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wtableid
    {
      get { return _wtableid; }
      set { _wtableid = value; }
    }
    private int _wchairid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wchairid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wchairid
    {
      get { return _wchairid; }
      set { _wchairid = value; }
    }
    private string _szpassword;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"szpassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szpassword
    {
      get { return _szpassword; }
      set { _szpassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestFailure")]
  public partial class RequestFailure : global::ProtoBuf.IExtensible
  {
    public RequestFailure() {}
    
    private int _errorCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorCode
    {
      get { return _errorCode; }
      set { _errorCode = value; }
    }
    private string _szDescribeString;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"szDescribeString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string szDescribeString
    {
      get { return _szDescribeString; }
      set { _szDescribeString = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_UserStatus")]
  public partial class GR_UserStatus : global::ProtoBuf.IExtensible
  {
    public GR_UserStatus() {}
    
    private string _dwUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dwUserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dwUserID
    {
      get { return _dwUserID; }
      set { _dwUserID = value; }
    }
    private gt_msg.tagUserStatus _UserStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public gt_msg.tagUserStatus UserStatus
    {
      get { return _UserStatus; }
      set { _UserStatus = value; }
    }
    private long _lScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lScore
    {
      get { return _lScore; }
      set { _lScore = value; }
    }
    private long _lInsure;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lInsure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lInsure
    {
      get { return _lInsure; }
      set { _lInsure = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_USER_READY")]
  public partial class GR_USER_READY : global::ProtoBuf.IExtensible
  {
    public GR_USER_READY() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_GameOpiton")]
  public partial class GR_GameOpiton : global::ProtoBuf.IExtensible
  {
    public GR_GameOpiton() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_TableStatus")]
  public partial class GR_TableStatus : global::ProtoBuf.IExtensible
  {
    public GR_TableStatus() {}
    
    private int _wTableID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wTableID
    {
      get { return _wTableID; }
      set { _wTableID = value; }
    }
    private gt_msg.TagTableStatus _TableStatus;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"TableStatus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public gt_msg.TagTableStatus TableStatus
    {
      get { return _TableStatus; }
      set { _TableStatus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_UserScore")]
  public partial class GR_UserScore : global::ProtoBuf.IExtensible
  {
    public GR_UserScore() {}
    
    private string _dwUserID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dwUserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dwUserID
    {
      get { return _dwUserID; }
      set { _dwUserID = value; }
    }
    private int _cbReason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cbReason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cbReason
    {
      get { return _cbReason; }
      set { _cbReason = value; }
    }
    private long _lScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lScore
    {
      get { return _lScore; }
      set { _lScore = value; }
    }
    private long _lInsure;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lInsure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lInsure
    {
      get { return _lInsure; }
      set { _lInsure = value; }
    }
    private int _dwWinCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dwWinCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dwWinCount
    {
      get { return _dwWinCount; }
      set { _dwWinCount = value; }
    }
    private int _dwLostCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dwLostCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dwLostCount
    {
      get { return _dwLostCount; }
      set { _dwLostCount = value; }
    }
    private int _dwDrawCount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"dwDrawCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dwDrawCount
    {
      get { return _dwDrawCount; }
      set { _dwDrawCount = value; }
    }
    private int _dwFleeCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"dwFleeCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dwFleeCount
    {
      get { return _dwFleeCount; }
      set { _dwFleeCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GR_UserScoreChange")]
  public partial class GR_UserScoreChange : global::ProtoBuf.IExtensible
  {
    public GR_UserScoreChange() {}
    
    private long _lScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lScore
    {
      get { return _lScore; }
      set { _lScore = value; }
    }
    private long _lInsure;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lInsure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lInsure
    {
      get { return _lInsure; }
      set { _lInsure = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GR_UserStandUp")]
  public partial class CMD_GR_UserStandUp : global::ProtoBuf.IExtensible
  {
    public CMD_GR_UserStandUp() {}
    
    private int _wTableID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wTableID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wTableID
    {
      get { return _wTableID; }
      set { _wTableID = value; }
    }
    private int _wChairID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wChairID
    {
      get { return _wChairID; }
      set { _wChairID = value; }
    }
    private bool _cbForceLeave;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cbForceLeave", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbForceLeave
    {
      get { return _cbForceLeave; }
      set { _cbForceLeave = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_GR_USEREXIT")]
  public partial class CMD_GR_USEREXIT : global::ProtoBuf.IExtensible
  {
    public CMD_GR_USEREXIT() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_StatusFreeResponse")]
  public partial class OXEX_StatusFreeResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_StatusFreeResponse() {}
    
    private long _lCellScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lCellScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lCellScore
    {
      get { return _lCellScore; }
      set { _lCellScore = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _lTurnScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lTurnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTurnScore
    {
      get { return _lTurnScore; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lCollectScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"lCollectScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lCollectScore
    {
      get { return _lCollectScore; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _szGameRoomName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"szGameRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> szGameRoomName
    {
      get { return _szGameRoomName; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_StatusCallResponse")]
  public partial class OXEX_StatusCallResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_StatusCallResponse() {}
    
    private int _wCallBanker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wCallBanker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wCallBanker
    {
      get { return _wCallBanker; }
      set { _wCallBanker = value; }
    }
    private bool _cbDynamicJoin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cbDynamicJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbDynamicJoin
    {
      get { return _cbDynamicJoin; }
      set { _cbDynamicJoin = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cbPlayStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cbPlayStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbPlayStatus
    {
      get { return _cbPlayStatus; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lTurnScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"lTurnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTurnScore
    {
      get { return _lTurnScore; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lCollectScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(5, Name=@"lCollectScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lCollectScore
    {
      get { return _lCollectScore; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _szGameRoomName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"szGameRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> szGameRoomName
    {
      get { return _szGameRoomName; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_StatusScoreResponse")]
  public partial class OXEX_StatusScoreResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_StatusScoreResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _cbPlayStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cbPlayStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbPlayStatus
    {
      get { return _cbPlayStatus; }
    }
  
    private bool _cbDynamicJoin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cbDynamicJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbDynamicJoin
    {
      get { return _cbDynamicJoin; }
      set { _cbDynamicJoin = value; }
    }
    private long _lTurnMaxScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lTurnMaxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lTurnMaxScore
    {
      get { return _lTurnMaxScore; }
      set { _lTurnMaxScore = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _lTableScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"lTableScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTableScore
    {
      get { return _lTableScore; }
    }
  
    private int _wBankerUser;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"wBankerUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wBankerUser
    {
      get { return _wBankerUser; }
      set { _wBankerUser = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _szGameRoomName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"szGameRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> szGameRoomName
    {
      get { return _szGameRoomName; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lTurnScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(7, Name=@"lTurnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTurnScore
    {
      get { return _lTurnScore; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lCollectScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"lCollectScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lCollectScore
    {
      get { return _lCollectScore; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_StatusPlayResponse")]
  public partial class OXEX_StatusPlayResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_StatusPlayResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _cbPlayStatus = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cbPlayStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbPlayStatus
    {
      get { return _cbPlayStatus; }
    }
  
    private bool _cbDynamicJoin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cbDynamicJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool cbDynamicJoin
    {
      get { return _cbDynamicJoin; }
      set { _cbDynamicJoin = value; }
    }
    private long _lTurnMaxScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lTurnMaxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lTurnMaxScore
    {
      get { return _lTurnMaxScore; }
      set { _lTurnMaxScore = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _lTableScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"lTableScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTableScore
    {
      get { return _lTableScore; }
    }
  
    private int _wBankerUser;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"wBankerUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wBankerUser
    {
      get { return _wBankerUser; }
      set { _wBankerUser = value; }
    }
    private readonly global::System.Collections.Generic.List<gt_msg.HandCardData> _cbHandCardData = new global::System.Collections.Generic.List<gt_msg.HandCardData>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cbHandCardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gt_msg.HandCardData> cbHandCardData
    {
      get { return _cbHandCardData; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _bOxCard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"bOxCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> bOxCard
    {
      get { return _bOxCard; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lTurnScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(8, Name=@"lTurnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lTurnScore
    {
      get { return _lTurnScore; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lCollectScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(9, Name=@"lCollectScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lCollectScore
    {
      get { return _lCollectScore; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _szGameRoomName = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"szGameRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> szGameRoomName
    {
      get { return _szGameRoomName; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_CallBankerResponse")]
  public partial class OXEX_CallBankerResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_CallBankerResponse() {}
    
    private int _wCallBanker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wCallBanker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wCallBanker
    {
      get { return _wCallBanker; }
      set { _wCallBanker = value; }
    }
    private bool _bFirstTimes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bFirstTimes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bFirstTimes
    {
      get { return _bFirstTimes; }
      set { _bFirstTimes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_GameStartResponse")]
  public partial class OXEX_GameStartResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_GameStartResponse() {}
    
    private long _lTurnMaxScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lTurnMaxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lTurnMaxScore
    {
      get { return _lTurnMaxScore; }
      set { _lTurnMaxScore = value; }
    }
    private int _wBankerUser;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wBankerUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wBankerUser
    {
      get { return _wBankerUser; }
      set { _wBankerUser = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_AddScoreResponse")]
  public partial class OXEX_AddScoreResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_AddScoreResponse() {}
    
    private int _wAddScoreUser;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wAddScoreUser", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wAddScoreUser
    {
      get { return _wAddScoreUser; }
      set { _wAddScoreUser = value; }
    }
    private long _lAddScoreCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lAddScoreCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lAddScoreCount
    {
      get { return _lAddScoreCount; }
      set { _lAddScoreCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_GameEndResponse")]
  public partial class OXEX_GameEndResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_GameEndResponse() {}
    
    private readonly global::System.Collections.Generic.List<long> _lGameTax = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lGameTax", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lGameTax
    {
      get { return _lGameTax; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _lGameScore = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"lGameScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> lGameScore
    {
      get { return _lGameScore; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cbOxCardType = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cbOxCardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbOxCardType
    {
      get { return _cbOxCardType; }
    }
  
    private readonly global::System.Collections.Generic.List<gt_msg.HandCardData> _cbHandCardData = new global::System.Collections.Generic.List<gt_msg.HandCardData>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cbHandCardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gt_msg.HandCardData> cbHandCardData
    {
      get { return _cbHandCardData; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cbHandCardCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"cbHandCardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbHandCardCount
    {
      get { return _cbHandCardCount; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HandCardData")]
  public partial class HandCardData : global::ProtoBuf.IExtensible
  {
    public HandCardData() {}
    
    private readonly global::System.Collections.Generic.List<int> _cbHandCardData = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cbHandCardData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbHandCardData
    {
      get { return _cbHandCardData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_SendCardResponse")]
  public partial class OXEX_SendCardResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_SendCardResponse() {}
    
    private readonly global::System.Collections.Generic.List<gt_msg.HandCardData> _cbCardData = new global::System.Collections.Generic.List<gt_msg.HandCardData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cbCardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gt_msg.HandCardData> cbCardData
    {
      get { return _cbCardData; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cbCardCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cbCardCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cbCardCount
    {
      get { return _cbCardCount; }
    }
  
    private bool _bAllAndroidUser;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bAllAndroidUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bAllAndroidUser
    {
      get { return _bAllAndroidUser; }
      set { _bAllAndroidUser = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_AllCardResponse")]
  public partial class OXEX_AllCardResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_AllCardResponse() {}
    
    private readonly global::System.Collections.Generic.List<bool> _bAICount = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bAICount", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> bAICount
    {
      get { return _bAICount; }
    }
  
    private readonly global::System.Collections.Generic.List<gt_msg.HandCardData> _cbCardData = new global::System.Collections.Generic.List<gt_msg.HandCardData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cbCardData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<gt_msg.HandCardData> cbCardData
    {
      get { return _cbCardData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_PlayerExitResponse")]
  public partial class OXEX_PlayerExitResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_PlayerExitResponse() {}
    
    private int _wPlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wPlayerID
    {
      get { return _wPlayerID; }
      set { _wPlayerID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_OpenCardResponse")]
  public partial class OXEX_OpenCardResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_OpenCardResponse() {}
    
    private int _wPlayerID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wPlayerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wPlayerID
    {
      get { return _wPlayerID; }
      set { _wPlayerID = value; }
    }
    private int _bOpen;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bOpen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bOpen
    {
      get { return _bOpen; }
      set { _bOpen = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_UserOutResponse")]
  public partial class OXEX_UserOutResponse : global::ProtoBuf.IExtensible
  {
    public OXEX_UserOutResponse() {}
    
    private int _wChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wChairID
    {
      get { return _wChairID; }
      set { _wChairID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_CallBankerRequest")]
  public partial class OXEX_CallBankerRequest : global::ProtoBuf.IExtensible
  {
    public OXEX_CallBankerRequest() {}
    
    private int _bBanker;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bBanker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bBanker
    {
      get { return _bBanker; }
      set { _bBanker = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_SPECIALRequest")]
  public partial class OXEX_SPECIALRequest : global::ProtoBuf.IExtensible
  {
    public OXEX_SPECIALRequest() {}
    
    private int _wUserChairID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"wUserChairID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wUserChairID
    {
      get { return _wUserChairID; }
      set { _wUserChairID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_AddScoreRequest")]
  public partial class OXEX_AddScoreRequest : global::ProtoBuf.IExtensible
  {
    public OXEX_AddScoreRequest() {}
    
    private long _lScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lScore
    {
      get { return _lScore; }
      set { _lScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OXEX_OxCardRequest")]
  public partial class OXEX_OxCardRequest : global::ProtoBuf.IExtensible
  {
    public OXEX_OxCardRequest() {}
    
    private int _bOX;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bOX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bOX
    {
      get { return _bOX; }
      set { _bOX = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinFreeRequestoxex")]
  public partial class JoinFreeRequestoxex : global::ProtoBuf.IExtensible
  {
    public JoinFreeRequestoxex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinFreeResponseoxex")]
  public partial class JoinFreeResponseoxex : global::ProtoBuf.IExtensible
  {
    public JoinFreeResponseoxex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForceExitTableRequestoxex")]
  public partial class ForceExitTableRequestoxex : global::ProtoBuf.IExtensible
  {
    public ForceExitTableRequestoxex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ForceExitTableResponseoxex")]
  public partial class ForceExitTableResponseoxex : global::ProtoBuf.IExtensible
  {
    public ForceExitTableResponseoxex() {}
    
    private gt_msg.ForceExitTableResponseoxex.Code _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public gt_msg.ForceExitTableResponseoxex.Code code
    {
      get { return _code; }
      set { _code = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=0)]
      Normal = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GiveUp", Value=1)]
      GiveUp = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoEnoughMoney", Value=2)]
      NoEnoughMoney = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeTable", Value=3)]
      ChangeTable = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayingNoExit", Value=4)]
      PlayingNoExit = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameReadyRequestoxex")]
  public partial class GameReadyRequestoxex : global::ProtoBuf.IExtensible
  {
    public GameReadyRequestoxex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameReadyResponseoxex")]
  public partial class GameReadyResponseoxex : global::ProtoBuf.IExtensible
  {
    public GameReadyResponseoxex() {}
    
    private gt_msg.GameReadyResponseoxex.Code _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public gt_msg.GameReadyResponseoxex.Code code
    {
      get { return _code; }
      set { _code = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _playerReady = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"playerReady", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> playerReady
    {
      get { return _playerReady; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Failed", Value=1)]
      Failed = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRankListRequestoxex")]
  public partial class GameRankListRequestoxex : global::ProtoBuf.IExtensible
  {
    public GameRankListRequestoxex() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRankListResponseoxex")]
  public partial class GameRankListResponseoxex : global::ProtoBuf.IExtensible
  {
    public GameRankListResponseoxex() {}
    
    private gt_msg.GameRankListResponseoxex.Code _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public gt_msg.GameRankListResponseoxex.Code code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _day_win_chips = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"day_win_chips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> day_win_chips
    {
      get { return _day_win_chips; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _all_times = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"all_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> all_times
    {
      get { return _all_times; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _all_chips = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"all_chips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> all_chips
    {
      get { return _all_chips; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Ok", Value=0)]
      Ok = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Failed", Value=1)]
      Failed = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}