// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/user.proto

package cmd.user;

public interface LoginOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string username = 1;
  /**
   * <code>required string username = 1;</code>
   */
  boolean hasUsername();
  /**
   * <code>required string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>required string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  // required string password = 2;
  /**
   * <code>required string password = 2;</code>
   */
  boolean hasPassword();
  /**
   * <code>required string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>required string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
