namespace Mogo.RPC
{
    using System;

    public enum CampaignErrorCode : ushort
    {
        ERR_ACTIVITY_GET_ACTIVITY_LEFT_TIME_NOT_EXIT = 0x10,
        ERR_ACTIVITY_GET_ACTIVITY_LEFT_TIME_NOT_STARTED = 0x11,
        ERR_ACTIVITY_INVITE_AC_NOT_EXIST = 6,
        ERR_ACTIVITY_INVITE_ALLREADY_INVITE = 7,
        ERR_ACTIVITY_INVITE_NOT_EXIT = 4,
        ERR_ACTIVITY_INVITE_NOT_FRIEND = 3,
        ERR_ACTIVITY_INVITE_NOT_ONLINE = 5,
        ERR_ACTIVITY_INVITE_RESP_NOT_EXIST = 8,
        ERR_ACTIVITY_INVITE_SELF = 2,
        ERR_ACTIVITY_JOIN_ALLREADY = 14,
        ERR_ACTIVITY_JOIN_LEVEL_NOT_MACTH = 11,
        ERR_ACTIVITY_JOIN_LEVEL_TIMES_OUT = 12,
        ERR_ACTIVITY_JOIN_NOT_EXIST = 10,
        ERR_ACTIVITY_JOIN_NOT_STARTED = 9,
        ERR_ACTIVITY_NOT_EXIST = 1,
        ERR_ACTIVITY_TOWER_DEFENCE_MATCH_FAIL = 13
    }
}

