namespace Mogo.RPC
{
    using System;

    public enum MSGIDType : ushort
    {
        ALLAPP_ONTICK = 0x65,
        ALLAPP_SETTIME = 0x66,
        ALLAPP_SHUTDOWN_SERVER = 0x67,
        BASEAPP_CLIENT_LOGIN = 0x20,
        BASEAPP_CLIENT_MOVE_REQ = 0x22,
        BASEAPP_CLIENT_REFUSE_RELOGIN = 0x15,
        BASEAPP_CLIENT_RELOGIN = 0x25,
        BASEAPP_CLIENT_RPC2CELL_VIA_BASE = 0x23,
        BASEAPP_CLIENT_RPCALL = 0x21,
        CLIENT_AOI_DEL_ENTITY = 15,
        CLIENT_AOI_ENTITIES = 8,
        CLIENT_AOI_NEW_ENTITY = 9,
        CLIENT_AVATAR_ATTRI_SYNC = 4,
        CLIENT_CHECK_RESP = 20,
        CLIENT_ENTITY_ATTACHED = 3,
        CLIENT_ENTITY_CELL_ATTACHED = 10,
        CLIENT_ENTITY_POS_PULL = 0x10,
        CLIENT_ENTITY_POS_SYNC = 6,
        CLIENT_ENTITY_POS_TELEPORT = 0x12,
        CLIENT_LOGIN_RESP = 1,
        CLIENT_NOTIFY_ATTACH_BASEAPP = 2,
        CLIENT_OTHER_ENTITY_ATTRI_SYNC = 11,
        CLIENT_OTHER_ENTITY_MOVE_REQ = 13,
        CLIENT_OTHER_ENTITY_POS_PULL = 0x11,
        CLIENT_OTHER_ENTITY_POS_SYNC = 12,
        CLIENT_OTHER_ENTITY_TELEPORT = 0x13,
        CLIENT_RPC_RESP = 5,
        LOGINAPP_CHECK = 30,
        LOGINAPP_LOGIN = 0x1f,
        LOGINAPP_MODIFY_LOGIN_FLAG = 0x1006,
        LOGINAPP_NOTIFY_CLIENT_TO_ATTACH = 0x1008,
        LOGINAPP_SELECT_ACCOUNT_CALLBACK = 0x1007,
        MAX_CLIENT_MSGID = 50,
        NOTIFY_CLIENT_DEFUSE_LOGIN = 0x16
    }
}

