//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EPageModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(EPageMode));
		L.RegVar("DoNothing", get_DoNothing, null);
		L.RegVar("HideOtherOnly", get_HideOtherOnly, null);
		L.RegVar("HideOtherAndNeedBack", get_HideOtherAndNeedBack, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_DoNothing(IntPtr L)
	{
		ToLua.Push(L, EPageMode.DoNothing);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HideOtherOnly(IntPtr L)
	{
		ToLua.Push(L, EPageMode.HideOtherOnly);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_HideOtherAndNeedBack(IntPtr L)
	{
		ToLua.Push(L, EPageMode.HideOtherAndNeedBack);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		EPageMode o = (EPageMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

