DB_TEMPLATE_EQUIP =
{
	[1] = {name = "weapon_sword_1", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = nil, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 98, element = nil, attack = 15, defense = 0, mAttack = 0, speed = 0, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 200, suit = 0},
	[2] = {name = "weapon_sword_2", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {12,0,0,0}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 96, element = nil, attack = 24, defense = 0, mAttack = 0, speed = -1, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 360, suit = 0},
	[3] = {name = "weapon_sword_3", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {15,0,10,0}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 97, element = nil, attack = 32, defense = 0, mAttack = 5, speed = 0, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 600, suit = 0},
	[4] = {name = "weapon_sword_4", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {18,0,0,0}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 94, element = nil, attack = 42, defense = 0, mAttack = 0, speed = 1, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 3, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 1000, suit = 0},
	[5] = {name = "weapon_sword_5", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {22,0,0,20}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 92, element = nil, attack = 50, defense = 3, mAttack = 0, speed = -2, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 4, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 1500, suit = 0},
	[6] = {name = "weapon_sword_6", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {24,0,16,0}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 95, element = nil, attack = 60, defense = 0, mAttack = 4, speed = 2, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 2200, suit = 0},
	[7] = {name = "weapon_sword_7", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {32,20,0,0}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 93, element = nil, attack = 76, defense = -8, mAttack = 0, speed = 0, hitPoint = 0, manaPoint = 0, stamina = 0, luck = -3, resist = nil, accuracy = 0, avoid = 0, critical = 8, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 3100, suit = 0},
	[8] = {name = "weapon_sword_8", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {40,0,24,32}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 98, element = nil, attack = 90, defense = 6, mAttack = 8, speed = 0, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 4200, suit = 0},
	[9] = {name = "weapon_sword_9", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {50,30,0,40}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 96, element = nil, attack = 110, defense = 0, mAttack = 5, speed = 3, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 20, buff = nil, debuff = nil, magic = "", skill = "", price = 4200, suit = 0},
	[10] = {name = "weapon_sword_10", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {60,45,30,50}, mainValue = "attack", rangeType = "", rangeValue = 1, hitRate = 94, element = nil, attack = 150, defense = 10, mAttack = 0, speed = 5, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 10, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 4200, suit = 0},
	[11] = {name = "weapon_sword_11", icon = "weapon_sword", sound = "", type = 0, part = 0, requirement = {70,50,40,60}, mainValue = "attack", rangeType = "", rangeValue = 2, hitRate = 98, element = nil, attack = 200, defense = 15, mAttack = 10, speed = 10, hitPoint = 0, manaPoint = 0, stamina = 0, luck = 0, resist = nil, accuracy = 0, avoid = 0, critical = 0, counter = 0, movePoint = 0, atkTimes = 0, actionTwice = false, moveMagic = false, hpSave = 0, mpSave = 0, absorb = 0, hitMp = 0, hpRestore = 0, mpRestore = 0, spFast = 0, buff = nil, debuff = nil, magic = "", skill = "", price = 4200, suit = 0}
}

function TemplateEquipGet()
	return nil
end